data <- data|> 
  rename(
    socmedmonitor = v2smgovsmmon_osp,
    socmedsd = v2smgovsm_osp,
    govintsd = v2smgovshut_osp,
    socmedalt = v2smgovsmalt_osp,
    contentreg = v2smregapp_osp,
    captoreg = v2smregcap_osp,
    intlegreg = v2smregcon_osp,
    intfilter = v2smgovfilprc_osp,
    cybseccap = v2smgovcapsec_osp,
    socmedcen = v2smgovsmcenprc_osp,
    fraction = v2smmefra_osp,
    orgoffviol = v2smorgviol_osp,
    avecituse = v2smorgavgact_osp,
    eliteuse = v2smorgelitact_osp,
    forgovdiss = v2smfordom_osp,
    gdppc = wdi_gdpcapcon2015,
    gdpgr = wdi_gdpgr,
    inflation = wdi_inflation,
    popden = wdi_popden,
    popgr = wdi_popgr,
    trade = wdi_trade,
    cybatt = cyberattacks_recode,
    ffrel = v2clrelig,
    polar = v2smpolsoc_osp
  ) 
